<?php

require_once dirname(__FILE__).'\..\src\formHelper.php';

if (!defined('PHPUnit_MAIN_METHOD')) {
    require 'PHPUnit/Autoload.php' ;
}

/**
 * Test class for BACKUP.
 * Generated by PHPUnit on 2012-02-09 at 16:51:21.
 */
class AjaxTest extends PHPUnit_Framework_TestCase
{

    /**
     * Chеcking wrong query in sqldump
     * @covers BACKUP::restore
     */
    public function testFormHelper()
    {
        $result=<<<RESULT
        <dd>
        <label>
               <select name='xxx'><option value='123' selected>123</option><option value='456'>456</option><option value='789'>789</option></select>
            </label> <br>
            <label>
               <input type="text" name="user" value="root">   - name
            </label> <br>
            <label>
               <input type="password" name="pass" value="111"> - password
            </label> <br>
            <label>
               <input type="text" name="base" value="tmp">  - base name
            </label> <br>
            <label>
               <input type="text" name="host" value="localhost"> - host
            </label> <br>
            <fieldset><legend>method</legend>
            <label>
               <input type="radio" name="method" value="sql.gz">  gzip <br>
            </label>
            <label>
               <input type="radio" name="method" value="sql"> sql  <br>
            </label>
            <label>
               <input type="radio" name="method" value="sql.bz2" checked> bz2 <br>
            </label>
            </fieldset>
            <label>
               <input type="submit" name="saveatserver" value="Save at server"> <br>
            </label>
        </dd>
RESULT;

        $text=<<<HTML
        <dd>
        <label>
               <select name='xxx'><option value='123'>123</option><option value='456'>456</option><option value='789'>789</option></select>
            </label> <br>
            <label>
               <input type="text" name="user">   - name
            </label> <br>
            <label>
               <input type="password" name="pass"> - password
            </label> <br>
            <label>
               <input type="text" name="base">  - base name
            </label> <br>
            <label>
               <input type="text" name="host"> - host
            </label> <br>
            <fieldset><legend>method</legend>
            <label>
               <input type="radio" name="method" value="sql.gz">  gzip <br>
            </label>
            <label>
               <input type="radio" name="method" value="sql"> sql  <br>
            </label>
            <label>
               <input type="radio" name="method" value="sql.bz2"> bz2 <br>
            </label>
            </fieldset>
            <label>
               <input type="submit" name="saveatserver" value="Save at server"> <br>
            </label>
        </dd>
HTML;
        $opt=array (
                'saveatserver' => '',
                'method' => 'sql.bz2',
                'user' => 'root',
                'pass' => '111',
                'host' => 'localhost',
                'base' => 'tmp',
                'xxx'=>123
            );
        $this->assertEquals(form_helper($text,$opt),$result) ;

     }
}

if (!defined('PHPUnit_MAIN_METHOD')) {
    $suite = new PHPUnit_Framework_TestSuite('AjaxTest');
    PHPUnit_TextUI_TestRunner::run( $suite);
}


?>
